from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog
import sys
from backend import code_message, code, decode

class Ui_MainWindow(object):

    def decode_img(self):
        orig = self.lineEdit_2.text()
        coded = self.lineEdit_3.text()
        mode = self.comboBox_2.currentText()
        msg = decode(coded, orig, mode)
        self.textEdit_2.setText(msg)

    def generate_pic(self):
        text_to_code = self.textEdit.toPlainText()
        coded_text = code_message(text_to_code)
        orig_img_path = self.lineEdit.text()
        default_name = "suspicious_img"
        mode = self.comboBox_2.currentText()
        print(mode)
        code(orig_img_path, coded_text, default_name, mode)
        path_to_new_file = "/".join(orig_img_path.split("/")[:-1]) + "/" + default_name + ".jpg"
        self.label_3.setStyleSheet(f'background-image : url({path_to_new_file}); border: 2px solid blue')


    def browse_files(self, link_to):
        file_name = QFileDialog.getOpenFileName(None, "Open file", "C:\\", "JPEG (*.jpg)")
        link_to.setText(file_name[0])

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 788)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1121, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 281, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 371, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 551, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 110, 1101, 181))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(270, 310, 511, 401))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 320, 161, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(580, 40, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(842, 310, 191, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(920, 40, 131, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(770, 40, 141, 21))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 281, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 311, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 40, 501, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 100, 501, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 190, 1081, 521))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 211, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 40, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 100, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(910, 50, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(760, 50, 151, 20))
        self.label_9.setObjectName("label_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(910, 120, 111, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шифратор изображений"))
        self.label_2.setText(_translate("MainWindow", "Введите текст для шифровки в изображении"))
        self.label.setText(_translate("MainWindow", "Укажите путь до файла  с исходной каритнкой"))
        self.label_4.setText(_translate("MainWindow", "Итоговое изображение:"))

        self.pushButton.setText(_translate("MainWindow", "Найти файл"))
        self.pushButton.clicked.connect(lambda: self.browse_files(self.lineEdit))

        self.pushButton_2.setText(_translate("MainWindow", "Сгенерировать изображение"))
        self.pushButton_2.clicked.connect(lambda: self.generate_pic())
        self.label_8.setText(_translate("MainWindow", "Алгоритм шифрования"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Зашифровать"))
        self.label_5.setText(_translate("MainWindow", "Укажите путь до файла с исходной картинкой:"))
        self.label_6.setText(_translate("MainWindow", "Укажите путь до файла с шифром:"))
        self.label_7.setText(_translate("MainWindow", "Зашифрованное послание"))

        self.pushButton_3.setText(_translate("MainWindow", "Найти файл"))
        self.pushButton_3.clicked.connect(lambda: self.browse_files(self.lineEdit_2))

        self.pushButton_4.setText(_translate("MainWindow", "Найти файл"))
        self.pushButton_4.clicked.connect(lambda: self.browse_files(self.lineEdit_3))
        self.label_9.setText(_translate("MainWindow", "Алгоритм шифрования"))
        self.pushButton_5.setText(_translate("MainWindow", "Расшифровать"))
        self.pushButton_5.clicked.connect(lambda : self.decode_img())
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Расшифровать"))

        self.comboBox_2.addItem("Нет")
        self.comboBox_2.addItem("Виженер")

        self.comboBox.addItem("Нет")
        self.comboBox.addItem("Виженер")


app = QApplication(sys.argv)
window = QMainWindow()
Ui_MainWindow().setupUi(window)
window.setFixedWidth(1125)
window.setFixedHeight(788)
window.show()
sys.exit(app.exec_())
